/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class OxfordDictionaryTest {
    @Test public void testSomeLibraryMethod() {
        OxfordDictionary classUnderTest = new OxfordDictionary();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
